# Generated by Django 5.0.1 on 2024-02-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankingtable', '0002_alter_product_name_alter_product_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alias',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
