# Generated by Django 5.0.1 on 2024-02-27 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankingtable', '0003_product_alias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetclass',
            options={'verbose_name_plural': 'Asset classes'},
        ),
    ]
