# Generated by Django 5.0.1 on 2024-02-27 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsHeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=10)),
                ('measurement', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='NewsReleaseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateField()),
                ('value_actual', models.FloatField()),
                ('value_previous', models.FloatField()),
                ('value_forecast', models.FloatField()),
                ('impact', models.CharField(max_length=5)),
                ('headline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analysis.newsheadline')),
            ],
        ),
    ]
