# Generated by Django 5.0.1 on 2024-02-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsheadline',
            name='definition',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
