# Generated by Django 5.0.1 on 2024-03-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_alter_newsreleasedata_value_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsheadline',
            name='sector',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
