# Generated by Django 5.0.1 on 2024-03-31 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_alter_newsheadline_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsheadline',
            name='abbreviation',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
